name: ci-trigger

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        run: |
          export TAG="${{ github.ref_name }}" \
          ; \
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cwlu2001/docker-build/actions/workflows/selfsigned-ssl.yml/dispatches \
            -d '{"ref":"master","inputs":{"tag":"'$TAG'"}}'
